#ifndef TASK_PRIORITIES_H_
#define TASK_PRIORITIES_H_


#define WIFI_TASK_PRIORITY (tskIDLE_PRIORITY  + 10)
#define BLE_INFO_TASK_PRIORITY (tskIDLE_PRIORITY  + 10)

#define CDC_TASK_PRIORITY (tskIDLE_PRIORITY  + 5)
#define USBH_TASK_PRIORITY (tskIDLE_PRIORITY  + 2)
#define MIDI_TASK_PRIORITY (tskIDLE_PRIORITY  + 7)

#define ESP_LINK_TASK_PRIORITY (tskIDLE_PRIORITY  + 3)

#endif // TASK_PRIORITIES_H_