#ifndef _TONEXONE_H_
#define _TONEXONE_H_

#include "Adafruit_TinyUSB.h"
#include "usbh_cdc_handling.h"

#define TONEX_ONE_PID 0x00D1
#define TONEX_ONE_VID 0x1963


#define TONEX_ONE_DEFAULT_MIDI_CHANNEL 		9

// MIDI Control Change Mapping
// Delay
#define TONEX_ONE_DELAY_POSITION					1
#define TONEX_ONE_DELAY_POWER_CC					2
#define TONEX_ONE_DELAY_TYPE_CC					3
#define TONEX_ONE_DELAY_DIGITAL_SYNC_CC		4
#define TONEX_ONE_DELAY_DIGITAL_TIME_CC		5
#define TONEX_ONE_DELAY_DIGITAL_FEEDBACK_CC	6
#define TONEX_ONE_DELAY_DIGITAL_MODE_CC		7
#define TONEX_ONE_DELAY_DIGITAL_MIX_CC			8
#define TONEX_ONE_DELAY_TAPE_SYNC_CC			91
#define TONEX_ONE_DELAY_TAPE_TIME_CC			92
#define TONEX_ONE_DELAY_TAPE_FEEDBACK_CC		93
#define TONEX_ONE_DELAY_TAPE_MODE_CC			94
#define TONEX_ONE_DELAY_TAPE_MIX_CC				95

// Bypass
#define TONEX_ONE_BYPASS_CC						12

// Noise Gate
#define TONEX_ONE_COMP_POSITION					13
#define TONEX_ONE_GATE_POWER_CC					14
#define TONEX_ONE_GATE_THRESHOLD_CC				15
#define TONEX_ONE_GATE_RELEASE_CC				16
#define TONEX_ONE_GATE_DEPTH_CC					17

// Compressor
#define TONEX_ONE_COMP_POWER_CC					18
#define TONEX_ONE_COMP_THRESHOLD_CC				19
#define TONEX_ONE_COMP_GAIN_CC					20
#define TONEX_ONE_COMP_ATTACK_CC					21
#define TONEX_ONE_COMP_POSITION_CC				22

// EQ
#define TONEX_ONE_EQ_BASS_CC						23
#define TONEX_ONE_EQ_BASS_FREQ_CC				24
#define TONEX_ONE_EQ_MID_CC						25
#define TONEX_ONE_EQ_MIDQ_CC						26
#define TONEX_ONE_EQ_MID_FREQ_CC					27
#define TONEX_ONE_EQ_TREBLE_CC					28
#define TONEX_ONE_EQ_TREBLE_FREQ_CC				29
#define TONEX_ONE_EQ_POST_CC						30

// Modulation
#define TONEX_ONE_MOD_POSITION_CC				31
#define TONEX_ONE_MOD_POWER_CC					32
#define TONEX_ONE_MOD_TYPE_CC						33
#define TONEX_ONE_MOD_CHORUS_SYNC_CC			34
#define TONEX_ONE_MOD_CHORUS_RATE_CC			35
#define TONEX_ONE_MOD_CHORUS_DEPTH_CC			36
#define TONEX_ONE_MOD_CHORUS_LEVEL_CC			37
#define TONEX_ONE_MOD_TREM_SYNC_CC				38
#define TONEX_ONE_MOD_TREM_RATE_CC				39
#define TONEX_ONE_MOD_TREM_SHAPE_CC				40
#define TONEX_ONE_MOD_TREM_SPREAD_CC			41
#define TONEX_ONE_MOD_TREM_LEVEL_CC				42
#define TONEX_ONE_MOD_PHASER_SYNC_CC			43
#define TONEX_ONE_MOD_PHASER_RATE_CC			44
#define TONEX_ONE_MOD_PHASER_DEPTH_CC			45
#define TONEX_ONE_MOD_PHASER_LEVEL_CC			46
#define TONEX_ONE_MOD_FLANGER_SYNC_CC			47
#define TONEX_ONE_MOD_FLANGER_RATE_CC			48
#define TONEX_ONE_MOD_FLANGER_DEPTH_CC			49
#define TONEX_ONE_MOD_FLANGER_FEEDBACK_CC		50
#define TONEX_ONE_MOD_FLANGER_LEVEL_CC			51
#define TONEX_ONE_MOD_ROTARY_SYNC_CC			52
#define TONEX_ONE_MOD_ROTARY_SPEED_CC			53
#define TONEX_ONE_MOD_ROTARY_RADIUS_CC			54
#define TONEX_ONE_MOD_ROTARY_SPREAD_CC			55
#define TONEX_ONE_MOD_ROTARY_LEVEL_CC			56

// Reverb
#define TONEX_ONE_REVEB_SPRING1_TIME_CC		59
#define TONEX_ONE_REVEB_SPRING1_PREDELAY_CC	60
#define TONEX_ONE_REVEB_SPRING1_COLOR_CC		61
#define TONEX_ONE_REVEB_SPRING1_MIX_CC			62
#define TONEX_ONE_REVEB_SPRING2_TIME_CC		63
#define TONEX_ONE_REVEB_SPRING2_PREDELAY_CC	64
#define TONEX_ONE_REVEB_SPRING2_COLOR_CC		65
#define TONEX_ONE_REVEB_SPRING2_MIX_CC			66
#define TONEX_ONE_REVEB_SPRING3_TIME_CC		67
#define TONEX_ONE_REVEB_SPRING3_PREDELAY_CC	68
#define TONEX_ONE_REVEB_SPRING3_COLOR_CC		69
#define TONEX_ONE_REVEB_SPRING3_MIX_CC			70
#define TONEX_ONE_REVER_ROOM_TIME_CC			71
#define TONEX_ONE_REVER_ROOM_PREDELAY_CC		72
#define TONEX_ONE_REVER_ROOM_COLOR_CC			73
#define TONEX_ONE_REVER_ROOM_MIX_CC				74
#define TONEX_ONE_REVEB_POWER_CC					75
#define TONEX_ONE_REVEB_PLATE_TIME_CC			76
#define TONEX_ONE_REVEB_PLATE_PREDELAY_CC		77
#define TONEX_ONE_REVEB_PLATE_COLOR_CC			78
#define TONEX_ONE_REVEB_PLATE_MIX_CC			79
#define TONEX_ONE_REVEB_SPRING4_TIME_CC		80
#define TONEX_ONE_REVEB_SPRING4_PREDELAY_CC	81
#define TONEX_ONE_REVEB_SPRING4_COLOR_CC		82
#define TONEX_ONE_REVEB_SPRING4_MIX_CC			83
#define TONEX_ONE_REVEB_POSITION_CC				84
#define TONEX_ONE_REVERB_TYPE_CC					85

// Presets
#define TONEX_ONE_PRESET_DOWN_CC					86
#define TONEX_ONE_PRESET_UP_CC					87
// Amplifier Model


// Virtual IR Cab
#define TONEX_ONE_VIR_CAB_PRESENCE_CC			106
#define TONEX_ONE_VIR_CAB_DEPTH_CC				107
#define TONEX_ONE_VIR_CAB_RESO_CC				108
#define TONEX_ONE_VIR_CAB_M1_CC					109
#define TONEX_ONE_VIR_CAB_M1_X_CC				110
#define TONEX_ONE_VIR_CAB_M1_Z_CC				111
#define TONEX_ONE_VIR_CAB_M2_CC					112
#define TONEX_ONE_VIR_CAB_M2_X_CC				113
#define TONEX_ONE_VIR_CAB_M2_Z_CC				114
#define TONEX_ONE_VIR_CAB_BLEND_CC				115

#define TONEX_ONE_GLOBAL_BPM_CC					123
#define TONEX_ONE_GLOBAL_INPUT_TRIM_CC			124
#define TONEX_ONE_GLOBAL_CABSIM_BYPASS_CC		125
#define TONEX_ONE_GLOBAL_TEMPO_SOURCE_CC		126



void tonexOne_Init();
void tonexOne_SendHello();
uint8_t tonexOne_HandleReceivedData(char *rxData, uint16_t len);
void tonexOne_Process();
void tonexOne_SendGoToPreset(uint8_t presetNum);
void tonexOne_SendNextPreset();
void tonexOne_SendPreviousPreset();

#endif // _TONEXONE_H_